-- 1) Criacao das tabelas

CREATE TABLE CLIENTES (
    CODIGOCLIENTE INTEGER NOT NULL PRIMARY KEY,
    NOMECLIENTE VARCHAR(100) NOT NULL,
    CPFCLIENTE VARCHAR(11) NOT NULL)

CREATE TABLE CARRO (
    CODIGOCARRO INTEGER NOT NULL PRIMARY KEY,
    MODELO VARCHAR(50) NOT NULL,
    DATALANCAMENTO DATE NOT NULL)

CREATE TABLE VENDA (
    CODIGOVENDA INTEGER NOT NULL PRIMARY KEY,
    CODIGOCLIENTE INTEGER NOT NULL,
    CODIGOCARRO INTEGER NOT NULL,
    DATAVENDA DATE NOT NULL,
    VALOR NUMERIC NOT NULL,
    FOREIGN KEY (CODIGOCLIENTE) REFERENCES CLIENTES(CODIGOCLIENTE),
    FOREIGN KEY (CODIGOCARRO) REFERENCES CARRO(CODIGOCARRO))

-- 2) Quantidade de vendas do carro Marea

SELECT COUNT(*) AS QTDVENDAS
  FROM VENDA V
 INNER JOIN CARRO C 
    ON C.CODIGOCARRO = V.CODIGOCARRO
 WHERE C.MODELO = 'Marea'

-- 3) Quantidade de vendas do carro Uno por cliente

SELECT CL.NOMECLIENTE, COUNT(*) AS QTDVENDAS
  FROM VENDA V
 INNER JOIN CARRO C 
    ON C.CODIGOCARRO = V.CODIGOCARRO
 INNER JOIN CLIENTES CL 
    ON CL.CODIGOCLIENTE = V.CODIGOCLIENTE
 WHERE C.MODELO = 'Uno'
 GROUP BY CL.CODIGOCLIENTE, CL.NOMECLIENTE

-- 4) Clientes que não efetuaram venda

SELECT CL.CODIGOCLIENTE, CL.NOMECLIENTE
  FROM CLIENTES CL
  LEFT JOIN VENDA V ON V.CODIGOCLIENTE = CL.CODIGOCLIENTE
 WHERE V.CODIGOCLIENTE IS NULL

-- 5) Clientes sorteados

SELECT FIRST 15
       CL.CODIGOCLIENTE
     , CL.NOMECLIENTE
     , CL.CPFCLIENTE 
     , V.DATAVENDA
  FROM VENDA V
 INNER JOIN CLIENTES CL ON CL.CODIGOCLIENTE = V.CODIGOCLIENTE
 INNER JOIN CARRO C ON C.CODIGOCARRO = V.CODIGOCARRO
 WHERE C.MODELO = 'Marea'
   AND EXTRACT(YEAR FROM C.DATALANCAMENTO) = 2021
   AND CL.CPFCLIENTE LIKE '0%'
   AND CL.CODIGOCLIENTE NOT IN (SELECT V2.CODIGOCLIENTE
                                  FROM VENDA V2
                                  INNER JOIN CARRO C2 ON C2.CODIGOCARRO = V2.CODIGOCARRO
                                  WHERE C2.MODELO = 'Marea'
                                  GROUP BY V2.CODIGOCLIENTE
                                  HAVING COUNT(*) >= 2)
 ORDER BY V.DATAVENDA ASC

-- 2- Exclusao não sorteados

DELETE FROM VENDA V
 WHERE NOT EXISTS (SELECT 1
                     FROM VENDA V2
                    INNER JOIN CLIENTES CL
                       ON CL.CODIGOCLIENTE = V2.CODIGOCLIENTE
                    INNER JOIN CARRO C 
                       ON C.CODIGOCARRO = V2.CODIGOCARRO
                    WHERE V2.CODIGOCLIENTE = V.CODIGOCLIENTE
                      AND C.MODELO = 'Marea'
                      AND EXTRACT(YEAR FROM C.DATALANCAMENTO) = 2021
                      AND CL.CPFCLIENTE LIKE '0%'
                      AND (SELECT COUNT(*)
                             FROM VENDA V3
                            INNER JOIN CARRO C3 ON C3.CODIGOCARRO = V3.CODIGOCARRO
                            WHERE V3.CODIGOCLIENTE = V2.CODIGOCLIENTE
                              AND C3.MODELO = 'Marea') < 2)
